### ISSUE TITLE
POST/dataset return HTTP status code 201 (but docs says 200)

### ISSUE THREAD

**Issue by jarve** [FAIRDataTeam/FAIRDataPoint-Docs#35]
My (not at all beautiful) program uploads datasets to FDP via API documented by
https://fairsfair.fair-dtls.surf-hosted.nl/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config#/Metadata%3A%20Dataset/postDataset
which said  that OK code is 200. But in practice successful  POST return 201, which is right and
more accurate value. So please fix the docs. (Many frameworks creates automatic documentation based existing code or code based documentation to avoid this kind  of errors.)

My code is available https://github.com/CSCfi/metaxreader/blob/main/src/main/java/fi/csc/fair/JSONhandling.java
and line 100 require so iterations.

**Comment by MarekSuchanek** [comment]
Hello @jarve, thanks for reporting... 

I fixed this in https://github.com/FAIRDataTeam/FAIRDataPoint/pull/186, it will be part of the next release.

We actually create OpenAPI documentation from code using `springdoc-openapi-ui` but these endpoints are specified in runtime configuration (you create a Dataset resource definition, that adds `/dataset` and `/dataset/{uuid}` with various methods). OpenAPI for these is added (and changed or removed if necessary) by our service.
